install.packages("rvest")
install.packages("httr")
install.pakacges("sp")
install.packages("styler")
install.packages("gganimate")
install.packages("gifski")
install.packages("png")
install.packages("transformr")
